[project]
name = "lavalit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit-folium>=0.24.0",
    "streamlit>=1.41.1",
]
